# Generated by Django 3.2.9 on 2021-11-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211124_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default=1, max_length=100, verbose_name='Ваше имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(max_length=100, null=True, verbose_name='Ваша фамилия'),
        ),
    ]
